stages:
  stage_01:
    cmd: python stage_01.py # cmd --> The command to run the stage
    deps:
      - stage_01.py # deps --> The dependencies required for the stage
    outs:
      - artifact.txt


  stage_02:
    cmd: python stage_02.py
    deps:
      - artifact.txt
      - stage_02.py
  

  stage_03:
    cmd: python stage_03.py
    deps:
      - artifact.txt
      - stage_03.py









# dvc repro --> dvc repro is used to reproduce the pipeline stages defined in dvc.yaml.
# dvc dag --> dvc dag is used to visualize the pipeline stages and their dependencies in a directed acyclic graph (DAG) format.
